server:
  port: 10001
  #context-path: /manager
spring:
  datasource:
    url: jdbc:mysql://rm-uf6zk76064d7w040zto.mysql.rds.aliyuncs.com:3306/product_first?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: Lc20082001==
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 500000
      # 连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      # 连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      # 用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis服务器地址
    host: 121.4.64.161
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 0
    #redis配置结束
    blockWhenExhausted: true
#  rabbitmq:
#    host: 121.4.64.161
#    port: 5672
#    username: admin
#    password: admin
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    #驼峰下划线转换
    db-column-underline: true
swagger:
  enable: true